[package]
name = "safeall-gui"
version = "0.1.0"
edition = "2024"


[dependencies]
safeall-core.workspace = true

iced = { version = "0.14.0", features = ["tokio"] }
tokio.workspace = true

[lints.clippy]
pedantic = "warn"
