[package]
name = "safeall-core"
version = "0.1.0"
edition = "2024"

[lib]
name = "safeall"
path = "src/lib.rs"

[dependencies]
blake3 = "1.8.2"
futures = "0.3.31"
tokio.workspace = true

[lints.clippy]
pedantic = "warn"
