[package]
name = "safeall"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = { version = "1.8.2" }
clap = { version = "4.5.53", features = ["derive"] }
rayon = "1.11.0"

[profile.release]
debug = true
