[workspace]
members = [
    "safeall/safeall-core",
    "safeall/safeall-cli",
    "safeall/safeall-gui",
]
resolver = "3"

[workspace.dependencies]
safeall-core = { path = "safeall/safeall-core" }
tokio = { version = "1.48.0", features = ["fs", "rt-multi-thread", "sync", "macros"] }
